# Generated by Django 5.0.6 on 2024-06-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_orderitem_order_deliveryboy_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_address", models.CharField(max_length=255)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("delivery_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.customer",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
