# Generated by Django 5.0.6 on 2024-06-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.URLField(default="kisurgbnvklsi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
