# Generated by Django 5.0.6 on 2024-06-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_order_contact_order_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(default="Pending", max_length=255, null=True),
        ),
    ]
