# Generated by Django 5.0.6 on 2024-06-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_boy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="core.deliveryboy",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
