# Generated by Django 5.0.6 on 2024-06-10 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_boy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="core.deliveryboy",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ordered", "Ordered"),
                    ("Accepted by Restaurant", "Accepted by Restaurant"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Accepted by Delivery Boy", "Accepted by Delivery Boy"),
                    ("Picked Up", "Picked Up"),
                    ("Delivered", "Delivered"),
                ],
                default="Ordered",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.order",
                    ),
                ),
            ],
        ),
    ]
