# Generated by Django 5.0.6 on 2024-06-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_order_delivery_boy_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryboy",
            name="free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deliveryboy",
            name="status",
            field=models.CharField(
                choices=[("Online", "Online"), ("Offline", "Offline")],
                default="Offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.order",
            ),
        ),
    ]
