# Generated by Django 5.0.6 on 2024-06-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_deliveryboy_free_deliveryboy_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(null=True, upload_to="media/restaurant_images/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ordered", "Ordered"),
                    ("Accepted by Restaurant", "Accepted by Restaurant"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Accepted by Delivery Boy", "Accepted by Delivery Boy"),
                    ("Picked Up", "Picked Up"),
                    ("Delivered", "Delivered"),
                    ("Undelivered", "Undelivered"),
                    ("Reached Location", "Reached Location"),
                ],
                default="Ordered",
                max_length=50,
            ),
        ),
    ]
